spring.data.mongodb.uri=mongodb://root:example@mongo:27017/usersdb?authSource=admin
server.port=8080
spring.data.mongodb.auto-index-creation=false

ai.service.url=${AI_SERVICE_URL:http://ai-service:5000}
# Active Directory connection configuration
ldap.domain=incidentmgmt.local
ldap.url=ldap://192.168.5.128:389
ldap.rootDn=dc=incidentmgmt,dc=local