services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - user-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/admin
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
    depends_on:
      - mongo
    networks:
      - user-network

  user-service:
    build: .
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - user-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/usersdb?authSource=admin
      INCIDENT_CLASSIFIER_URL: http://incident-classifier:5000
      SOLUTION_SUGGEST_URL: http://solution-suggest:5001

  incident-classifier:
    build:
      context: ../ai
      dockerfile: dockerfile
    container_name: incident-classifier
    ports:
      - "5000:5000"
    volumes:
      - ../ai/models:/app/models
    networks:
      - user-network
    command: ["python", "app.py"]

  solution-suggest:
    build: 
      context: ../ai
      dockerfile: dockerfile
    container_name: solution-suggest
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - user-network
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/usersdb?authSource=admin
    command: ["python", "solution_suggest.py"]

networks:
  user-network:
    driver: bridge

volumes:
  mongo-data: