services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - user-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - user-network

  user-service:
    build: .
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - user-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/usersdb?authSource=admin
      AI_SERVICE_URL: http://ai-service:5000

  ai-service:
    image: ai-service  
    container_name: ai-service
    ports:
      - "5000:5000"
    networks:
      - user-network

networks:
  user-network:
    driver: bridge

volumes:
  mongo-data: